SELECT * FROM film_category;

-- 1. List the number of films per category.
SELECT 
    category.name AS category_name,
    COUNT(film_category.film_id) AS film_count
FROM film_category
JOIN category ON film_category.category_id = category.category_id
GROUP BY category.name;


-- 2. Retrieve the store ID, city, and country for each store.

SELECT 
    store.store_id,
    city.city,
    country.country
FROM store
JOIN address ON store.address_id = address.address_id
JOIN city ON address.city_id = city.city_id
JOIN country ON city.country_id = country.country_id;


-- Calculate the total revenue generated by each store in dollars.

select amount, staff_id from payment;
select staff_id, store_id from staff;

SELECT
   store.store_id,  
   SUM(payment.amount) AS total_revenue 
FROM payment
JOIN staff ON payment.staff_id = staff.staff_id
JOIN store ON staff.store_id = store.store_id
GROUP BY store.store_id;

-- Determine the average running time of films for each category.

SELECT 
	category.name AS category_name,
    AVG(film.length) AS avg_length_per_category
FROM film
JOIN film_category ON film.film_id = film_category.film_id
JOIN category ON film_category.category_id = category.category_id
GROUP BY category_name;







